
version: '3'
services: 
    web:
        build: .
        volumes: 
            - ".:/src"
        command: npm start
        container_name: my-app_web_1
        ports:
            - "3000:3000"
            - "9229:9229"
        environment: 
            NODE_ENV: development
            PORT: 3000